### ISSUE TITLE
Cannot connect to ODBC DSN: [SQL_ERROR]:[01000][0][[unixODBC][Driver Manager]Can't open lib '/usr/lib/oracle/11.2/client64/lib/libsqora.so.11.1' : file not found]

### ISSUE THREAD

**Issue by marlonrib** [den-is/zbx_oracle_odbc#1]
I'm doing this configuration through the zabbix proxy.

When adding the templete I get this error.

![image](https://user-images.githubusercontent.com/32168992/108452223-eaf2f400-7246-11eb-98d5-d56457f866c9.png)

![image](https://user-images.githubusercontent.com/32168992/108452292-0100b480-7247-11eb-9af2-26910befd955.png)

can you help me?

**Comment by den-is** [comment]
Hey @marlonrib 
Unfortunately, that my project is too old. :(
First of all, I do not have access to Zabbix.
Second, while the absence of Zabbix is easily fixable - I don't have any access to Oracle DBs right now and have no desire to gain it.
Sorry.

**Comment by marlonrib** [comment]
hello @den-is

I managed to solve the problem.

I created the file with the variables below and restarted the zabbix proxy.

```
[root@zabbix-proxy ~]# cat /etc/sysconfig/zabbix-proxy
ORACLE_HOME=/usr/lib/oracle/11.2/client64
LD_LIBRARY_PATH=/usr/lib/oracle/11.2/client64/lib:/usr/lib64
TNS_ADMIN=/usr/lib/oracle/11.2/client64/network/admin
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/lib/oracle/11.2/client64/lib

export ORACLE_HOME
export LD_LIBRARY_PATH
export TNS_ADMIN
export PATH

[root@zabbix-proxy ~]# strings -a /proc/<zabbix-proxy Main PID>/environ 
LANG=en_US.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/lib/oracle/11.2/client64/lib
CONFFILE=/etc/zabbix/zabbix_proxy.conf
ORACLE_HOME=/usr/lib/oracle/11.2/client64
LD_LIBRARY_PATH=/usr/lib/oracle/11.2/client64/lib:/usr/lib64
TNS_ADMIN=/usr/lib/oracle/11.2/client64/network/admin

```
Thanks.
